### Вычисления с помощью Numpy

In [185]:
# Задание 1
import numpy as np

a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7],])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [186]:
mean_a = np.array([np.mean(a[:, 0]), np.mean(a[:, 1])])

mean_a

array([2. , 8.4])

In [187]:
# Задание_2
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [188]:
# Задание_3
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
N = a.shape[0]
cov_a = a_centered_sp / (N - 1)
cov_a

2.0

In [189]:
# Задание_4
b =np.cov(np.transpose(a))
b


array([[1. , 2. ],
       [2. , 4.3]])

### Работа с данными в Pandas

In [201]:
# Задание 1
import pandas as pd
authors = pd.DataFrame({'author_id':[1, 2, 3, ],
                       'author_name' : ['Тургенев', 'Чехов', 'Островский', ]}, columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [216]:
book = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3, ],
                     'book' : ['Отцы и дети', 
                               'Рудин', 
                               'Дворянское гнездо', 
                               'Толстый и тонкий', 
                               'Дама с собачкой', 
                               'Гроза', 
                               'Таланты и поклонники', ],
                     'price' : [450, 300, 350, 500, 450, 370, 290]}, columns = ['author_id','book','price',])
book

author_id                  book  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [217]:
# Задание 2
authors_price = authors.merge(book)
authors_price

author_id author_name                  book  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [218]:
# Задание 3
authors_price.sort_values(by ='price').tail()

author_id author_name               book  price
2          1    Тургенев  Дворянское гнездо    350
5          3  Островский              Гроза    370
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
3          2       Чехов   Толстый и тонкий    500

In [219]:
# Задание 4
authors_stat = pd.DataFrame({'author_name' :authors_price['author_name'].unique(),
                             'min_price' :  [min(authors_price.loc[authors_price['author_name'] == authors_price['author_name'].unique()[i], 'price'].values) for i in range(len(authors_price['author_name'].unique()))],
                             'max_price' :  [max(authors_price.loc[authors_price['author_name'] == authors_price['author_name'].unique()[i], 'price'].values) for i in range(len(authors_price['author_name'].unique()))],
                             'mean_price':  [np.mean(authors_price.loc[authors_price['author_name'] == authors_price['author_name'].unique()[i], 'price'].values) for i in range(len(authors_price['author_name'].unique()))],}, 
                            columns = ['author_name', 'min_price', 'max_price', 'mean_price', ])
authors_stat

author_name  min_price  max_price  mean_price
0    Тургенев        300        450  366.666667
1       Чехов        450        500  475.000000
2  Островский        290        370  330.000000

In [220]:
# Задание 5
cover =['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая', ]
authors_price['cover'] = cover
authors_price

author_id author_name                  book  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [227]:
book_info = pd.pivot_table(authors_price, values = 'price', index = ['author_name'], 
                               columns = 'cover', aggfunc = np.sum, fill_value = 0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [232]:
book_info.to_pickle('./book_info.pkl')
book_info2 = pd.read_pickle('./book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950